version: "2"
services:
  web-patron:
    container_name: web-patron
    build: ./
    environment:
      CONFIG_FILE: /config/config.yml
      NODE_ENV: production
    volumes:
      - ./config:/config
    ports:
      - 3000:3000
